name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Configure git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Set remote URL for Hugging Face
      run: |
        git remote set-url origin https://KingArthur111:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/KingArthur111/DocuMind

    - name: Pull latest from Hugging Face repo to avoid conflicts
      run: |
        git fetch origin main
        git pull --rebase origin main || git merge origin/main

    - name: Push changes to Hugging Face
      run: |
        git push origin main
