name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Sync code and push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://KingArthur111:$HF_TOKEN@huggingface.co/spaces/KingArthur111/DocuMind
        git fetch origin main
        git pull --rebase origin main || git merge origin/main
        git push origin main
